"""
Django settings for cspherecx project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from pathlib import Path
from pathlib import Path
from datetime import timedelta
import os
from django.utils.translation import gettext_lazy as _
import django
from django.utils.encoding import smart_str
django.utils.encoding.smart_text = smart_str
from dotenv import load_dotenv
load_dotenv() 
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure--5euc51$#!rf9)q2^_9fgpnnd_8xireh==dy!q0he$h6^s)fda"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

SECRET_KEY = os.environ.get('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [ '192.168.1.157', 'localhost', '127.0.0.1']

GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', default='your-gemini-api-key')
GEMINI_MODEL = 'gemini-2.5-flash'  # Balanced for cost/performance
GEMINI_MODEL_PRO = 'gemini-2.5-pro'  # For complex analysis


# Application definition

INSTALLED_APPS = [
   'grappelli',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django.contrib.humanize',
    ### Allauth 
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    
    #### Installed apps
    "core",
    "accounts",
    'django_summernote',
    'surveys',
    'feedback',
    'cx_analytics',
    'rosetta',
    
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = "cspherecx.urls"
CSRF_TRUSTED_ORIGINS = ["http://127.0.0.1:8000"]

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "cspherecx.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        #"NAME": BASE_DIR / "db.sqlite3",
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

#LANGUAGE_CODE = "en-us"
LANGUAGE_CODE = 'en'  # or your default language

LANGUAGES = [
    ('en', 'English'),
    ('es', 'Spanish'),
    ('fr', 'French'),
    ('de', 'German'),
]
 
PARLER_LANGUAGES = {
    None: (
        { 'code': 'en',},
        { 'code': 'fr',},
    ),
    'default': {
        'fallback': ['en' ],
        'hide_untranslated': False
    }
}

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]


TIME_ZONE = "UTC"
USE_I18N = True
USE_L10N = True
USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_ROOT = os.path.join(BASE_DIR, "static_root")

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT=os.path.join(BASE_DIR, 'media/')

# Ensure media directories exist
MEDIA_DIRS = {
    'audio': Path(MEDIA_ROOT) / 'audio',
    'text': Path(MEDIA_ROOT) / 'text',
}

# Create directories if they don't exist
for directory in MEDIA_DIRS.values():
    directory.mkdir(parents=True, exist_ok=True)
    

MEDIA_ROOT=os.path.join(BASE_DIR, "media")

TAGS_URL = '/templatetags/'
TAGS_ROOT=os.path.join(BASE_DIR, "templatetags")

# Create directories if they don't exist
for directory in MEDIA_DIRS.values():
    os.makedirs(directory, exist_ok=True)
# Default primary key field type
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# For development (console backend)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
#For production (using SMTP) uncomment these lines for production
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER') # this email will be used to send emails
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD') # host email password required
DEFAULT_FROM_EMAIL = "Delight Admin"
PASSWORD_RESET_TIMEOUT = 14400
EMAIL_SUBJECT_PREFIX = '[CSphere CX Analytics]'


# Authentication backends
AUTHENTICATION_BACKENDS = [
    # Django default
    'django.contrib.auth.backends.ModelBackend',
    
    # django-allauth
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1
# Analysis Configuration
SENTIMENT_THRESHOLD = 0.7
THEME_MIN_CLUSTER_SIZE = 3
NPS_INFERENCE_ENABLED = True

# Allauth settings
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PKCE_ENABLED': True,
    },
    'facebook': {
        'METHOD': 'oauth2',
        'SDK_URL': '...',
        'SCOPE': ['email', 'public_profile'],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'INIT_PARAMS': {'cookie': True},
        'FIELDS': [
            'id',
            'first_name',
            'last_name',
            'middle_name',
            'name',
            'name_format',
            'picture',
            'short_name'
        ],
        'EXCHANGE_TOKEN': True,
        'VERIFIED_EMAIL': False,
        'VERSION': 'v13.0',
    }
}

